### ISSUE TITLE
Connect refused error when using `yogi serve`

### ISSUE THREAD

**Issue by ericf** [yui/yogi#1]
I'm getting the following connection refused error when using `yogi serve` and trying to navigate to either the user guide or API docs for a module (the tests work fine):

``` shell
Glare:app eferraiuolo$ yogi serve
yogi [info]  using yogi@0.0.14 on node@0.8.8
yogi [warn]  THIS IS EXPERIMENTAL, USE AT YOUR OWN RISK!!
yogi [info]  using module: app
yogi [info]  this is yui, using global path for all docs
yogi [info]  this is yui, using global path for all docs
yogi [info]  launching yuidoc --server 5001 --config /Users/eferraiuolo/Code/yui/yui3/src/common/api/yuidoc.json .
yogi [info]  this is yui, using global path for all docs
yogi [info]  launching selleck --server 5002 --project /Users/eferraiuolo/Code/yui/yui3/src/common/docs/
yogi [info]  adding tests route
yogi [info]  listening on: http://127.0.0.1:5000

stream.js:81
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
    at errnoException (net.js:768:11)
    at Object.afterConnect [as oncomplete] (net.js:759:19)
Glare:app eferraiuolo$ 

```

**Comment by davglass** [comment]
This was fixed a while back..
