### ISSUE TITLE
yogi serve crashes 

### ISSUE THREAD

**Issue by triptych** [yui/yogi#41]
Updated src to latest dev-master from upstream public repo.
Updated yogi via npm install yogi.
Node is version v.0.8.16

I cd to yui3/src
run "yogi serve"

I get:

yogi [info]  using yogi@0.0.61 on node@0.8.16
yogi [info]  adding tests route
yogi [info]  this is yui, using global path for all docs
yogi [info]  launching yuidoc --server 5001 --config /Users/awooldri/MyHome/Projects/yui/yuiwork/yui3/src/common/api/yuidoc.json
yogi [info]  this is yui, using global path for all docs
yogi [info]  launching selleck --server 5002 --project /Users/awooldri/MyHome/Projects/yui/yuiwork/yui3/src/common/docs/
yogi [info]  launching xdr server on port 5003
yogi [info]  listening on: http://127.0.0.1:5000
yogi [ERROR] selleck: execvp(): No such file or directory

I visit : http://127.0.0.1:5000/
 and under Docs and Stuff I click on 
"Examples and Landing page"

node server crashes with this error:

stream.js:81
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
    at errnoException (net.js:770:11)
    at Object.afterConnect [as oncomplete](net.js:761:19)

**Comment by triptych** [comment]
which selleck returns
/usr/local/bin/selleck

**Comment by triptych** [comment]
Looks like I had two instances of yogi -- after npm uninstall I still had yogi in another location. killing that one and re-installing fixed things.
