### ISSUE TITLE
Yogi Loader fails in gallery or other project directories

### ISSUE THREAD

**Issue by foxxtrot** [yui/yogi#59]
`yogi loader` should be able to generate metadata for properly structured folders of modules such as my gallery repo, with the following errors:

```
╰─➤  yogi loader                                                            1 ↵
yogi [info]  using yogi@0.0.44 on node@0.9.4-pre
yogi [info]  generating loader meta-data for: /home/craig/src/yui/yui-gallery
yogi [info]  storing module here: /home/craig/src/yui/yui-gallery/loader/js/yui3.js
yogi [info]  and json here: /home/craig/src/yui/yui-gallery/loader/js/yui3.json
are you sure you want to use the default settings? [Y/n] Y
yogi [bail] Something went very wrong here, could not find meta data to parse.
```

While those defaults aren't great in this use case, it should still work.

**Comment by davglass** [comment]
What repo is that? Can I see it? Did you run it from the root or from the root of the modules (`./src`)?

**Comment by foxxtrot** [comment]
It's this repo: https://github.com/foxxtrot/yui-gallery/

I was running from the project root, but I got these errors when run from src:

```
╭─craig@deepthought ~/src/yui/yui-gallery/src  ‹master› 
╰─➤  yogi loader
yogi [info]  using yogi@0.0.44 on node@0.9.4-pre
yogi [info]  generating loader meta-data for: /home/craig/src/yui/yui-gallery/src
yogi [info]  storing module here: /home/craig/src/yui/yui-gallery/src/loader/js/yui3.js
yogi [info]  and json here: /home/craig/src/yui/yui-gallery/src/loader/js/yui3.json
are you sure you want to use the default settings? [Y/n] y
yogi [info]  found 6 .json files to parse. parsing now..
yogi [info]  writing json: /home/craig/src/yui/yui-gallery/src/loader/js/yui3.json

fs.js:349
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
             ^
Error: ENOENT, no such file or directory '/home/craig/src/yui/yui-gallery/src/loader/js/yui3.json'
    at Object.fs.openSync (fs.js:349:18)
    at Object.fs.openSync (/usr/local/lib/node_modules/yogi/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.openSync (/usr/local/lib/node_modules/yogi/node_modules/cpr/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.openSync (/usr/local/lib/node_modules/yogi/node_modules/istanbul/node_modules/fileset/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.writeFileSync (fs.js:827:15)
    at Object.mods.writeJSON (/usr/local/lib/node_modules/yogi/lib/cmds/loader.js:201:12)
    at Object.mods.begin (/usr/local/lib/node_modules/yogi/lib/cmds/loader.js:305:14)
    at /usr/local/lib/node_modules/yogi/lib/cmds/loader.js:66:22
    at /usr/local/lib/node_modules/yogi/lib/util.js:210:13
    at Interface._onLine (readline.js:198:5)
```

Manually creating directories yui/js and loader/js fix the above error.

**Comment by davglass** [comment]
That version of yogi is pretty old, the latest is `yogi@0.0.68`

**Comment by foxxtrot** [comment]
Updating Yogi corrected the directory creation issue. Should have tried that first.
