### ISSUE TITLE
Shifter throws an error when using yogi server (as from 0.1.11)

### ISSUE THREAD

**Issue by ItsAsbreuk** [yui/yogi#85]
Maybe I'm doing something wrong (I am just diving into all the yogi-options), but for what I can tell, running yogi serve --> localhost:5000/shifter throws an error and will stop the yogi-server. I just noticed this after upgrading from 0.1.10 to 0.1.11

Browser:

```
[Back to yogi]

You can add parameters to the query string to use shifter options: /shifter?istanbul&quiet&foo=bar
cd /myworkingdir
$ shifter --walk --cache --istanbul
```

Terminal:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

I see the same when running yogi serve --watch (probably because that will run shifter under the hood during startup)

Regards,
Marco.

**Comment by ItsAsbreuk** [comment]
All right, found out why.
I started yogi serve in the parentDir of src

Starting the server inside src solved the problem.
Although yogi serve --watch stiil trows an error, but I make that another issue.

Marco
